// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "03d52497",
  git_describe: "03d52497-dirty",
  buildTime: "2026-01-28T08:19:10Z",
};
