// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "a8348941",
  git_describe: "v0.14.1",
  buildTime: "2026-01-28T03:43:05Z",
};
