// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "179ddf14",
  git_describe: "179ddf14-dirty",
  buildTime: "2026-01-28T09:25:57Z",
};
